### ISSUE TITLE
Only every 6 hours?

### ISSUE THREAD

**Issue by NiPaGe80** [arjun-dureja/SubWidget#1]
Is there is an possibility to make a live counter or update ever 30/60 minutes

**Comment by arjun-dureja** [comment]
Hi, unfortunately I can’t do a live counter but I can make it update more frequently. I’m just waiting for Google to increase my YouTube API quota and I’ll update the app.

**Comment by arjun-dureja** [comment]
App has been updated. The widget updates approximately every hour now.
