### ISSUE TITLE
Edit widget: Channel list is Empty

### ISSUE THREAD

**Issue by amannayak0007** [arjun-dureja/SubWidget#2]
![IMG_96110B79A256-1](https://user-images.githubusercontent.com/7374342/181780590-3a0b5312-e1fe-401c-9578-ad291c616967.jpeg)

**Comment by arjun-dureja** [comment]
I think you've got the wrong app

**Comment by amannayak0007** [comment]
I'm using iOS 16 beta. May be it's iOS issue.

**Comment by arjun-dureja** [comment]
Did you add a channel in the app? 

Also the code on master isn't ready for production yet, I recommend using the version on the App store.

**Comment by amannayak0007** [comment]
Yes, I have channels in the app. I can see the list of channels in the app, but I'm having trouble with widgets. Sure I'll use the app store version.
