### ISSUE TITLE
Does not work on macOS Sequoia.

### ISSUE THREAD

**Issue by TJK152** [arjun-dureja/SubWidget#3]
I am on a 2021 MacBook Pro 14 inch M1 Pro running the latest macOS 15 Sequoia. I bought this app for my phone and mac to keep track of my company's YouTube channel. It works fine on my iPhone 14 Pro with the latest iOS 18 release. On my mac, I try to add my channel and the app shows a blank pop-up and locks up where I have to force quit it.
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/375dbdb6-8016-4449-a4d3-185881ab191c">

**Comment by arjun-dureja** [comment]
Thanks for reporting. This is now fixed in version 9.8 (2.8 on the App Store)
